apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: tds-group-3
  labels:
    app: users-api
spec:
  type: ClusterIP
  selector:
    app: users-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
