apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: tds-group-3
spec:
  type: ClusterIP
  selector:
    app: users-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
